# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Diffwatch < Formula
  desc "Real-time CLI tool for watching file changes and visualizing diffs"
  homepage "https://github.com/deemkeen/diffwatch"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deemkeen/diffwatch/releases/download/v1.0.1/diffwatch_1.0.1_Darwin_x86_64.tar.gz"
      sha256 "241f0f824060a21e819cee1afd6d0e75606e6ab3a67e944522625224f64c3ec5"

      def install
        bin.install "diffwatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deemkeen/diffwatch/releases/download/v1.0.1/diffwatch_1.0.1_Darwin_arm64.tar.gz"
      sha256 "39d31359bb373252c3fc7998c7119a9e3f91d693e316975fb6442f5c6219ae63"

      def install
        bin.install "diffwatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deemkeen/diffwatch/releases/download/v1.0.1/diffwatch_1.0.1_Linux_x86_64.tar.gz"
      sha256 "385665fc9dcda38907ab3aaa685656fcf6ac3c25dcf9f8e4e8ac12cdd1e37466"
      def install
        bin.install "diffwatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deemkeen/diffwatch/releases/download/v1.0.1/diffwatch_1.0.1_Linux_arm64.tar.gz"
      sha256 "a9334fdcd22d2eeaa83b326a7ad370b175fef14236648d76dfee4da9b172f5a3"
      def install
        bin.install "diffwatch"
      end
    end
  end

  test do
    system "#{bin}/diffwatch", "-h"
  end
end
