# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Diffwatch < Formula
  desc "Real-time CLI tool for watching file changes and visualizing diffs"
  homepage "https://github.com/deemkeen/diffwatch"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deemkeen/diffwatch/releases/download/v1.0.1/diffwatch_1.0.1_Darwin_x86_64.tar.gz"
      sha256 "3a9a5d29cc21af8615e2697114f8a11b80d95a4d61c107ad900932e7598fa8e7"

      def install
        bin.install "diffwatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deemkeen/diffwatch/releases/download/v1.0.1/diffwatch_1.0.1_Darwin_arm64.tar.gz"
      sha256 "edf4d5f8e4746b4def13bbc4ee39e109333af796da74edc506d018ff591cc03b"

      def install
        bin.install "diffwatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deemkeen/diffwatch/releases/download/v1.0.1/diffwatch_1.0.1_Linux_x86_64.tar.gz"
      sha256 "1ea0afde26a6f46acd7da82bbafc491b37a1b01817bb39433b385cc686ade784"
      def install
        bin.install "diffwatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deemkeen/diffwatch/releases/download/v1.0.1/diffwatch_1.0.1_Linux_arm64.tar.gz"
      sha256 "e037f5e38055739e2f26f21ad2d380ade757493777264d1a413fc6b8ce533849"
      def install
        bin.install "diffwatch"
      end
    end
  end

  test do
    system "#{bin}/diffwatch", "-h"
  end
end
