# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Diffwatch < Formula
  desc "Real-time CLI tool for watching file changes and visualizing diffs"
  homepage "https://github.com/deemkeen/diffwatch"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deemkeen/diffwatch/releases/download/v1.0.0/diffwatch_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "34b4819a5d7cb1ed2f3c753c12f9c25635729f296b36aee28af6c0922c44ee7a"

      def install
        bin.install "diffwatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deemkeen/diffwatch/releases/download/v1.0.0/diffwatch_1.0.0_Darwin_arm64.tar.gz"
      sha256 "4cc7df087e6736d8e06a497b202236ac99d5b3cf1ec959d66563d21add2a3887"

      def install
        bin.install "diffwatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deemkeen/diffwatch/releases/download/v1.0.0/diffwatch_1.0.0_Linux_x86_64.tar.gz"
      sha256 "177d3e4ac3c63ceed6386bd7d0138d850eaf504f25db6f44a57de224c15baf7c"
      def install
        bin.install "diffwatch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deemkeen/diffwatch/releases/download/v1.0.0/diffwatch_1.0.0_Linux_arm64.tar.gz"
      sha256 "f60b5c43a32d4500e55016e10611b66404e457b792a939ca49df93685b003519"
      def install
        bin.install "diffwatch"
      end
    end
  end

  test do
    system "#{bin}/diffwatch", "-h"
  end
end
